### PR TITLE
ENG-2496 amended edit widget config for CMS single content widget

### PR DESCRIPTION
**Pull request by jeffgo10**

### CODE REVIEW

**Comment by g-di-martino** [comment]
Please, update the code to use the page object pattern and the API calls

**Review by g-di-martino — CHANGES_REQUESTED** [review]
Please, update the code to use the page object pattern and the API calls

**Review by g-di-martino — CHANGES_REQUESTED** [review]
Use rebase instead of merge when updating from develop, it keeps the history cleaner and avoid misunderstanding on the actual changes of the branch

**Comment by jeffgo10** [comment]
probably would be best if I'll just close this PR and open a new branch. my apologies

**Pull request closed without merging**
